name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-lates

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.1.6
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SERVER_USERNAME }}
        REMOTE_USER: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: '.'
        TARGET: '/var/www/html'
