name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to server
      run: rsync -avz -e "ssh -i ${{ secrets.SSH_PRIVATE_KEY }}" . ${{ secrets.SERVER_USERNAME }}@${{ secrets.REMOTE_HOST }}:/var/www/html/
